### ISSUE TITLE
I'm confused with Windows 2019 Server 64bit 

### ISSUE THREAD

**Issue by AntiTenzor** [zozzz/yapic.json#13]
I'm confused what is going on.
Any ideas are very warm welcome.

My steps:
1) Fresh installation of **Windows 2019 Server 64bit**
2) Python v3.7.5 is installed in    **C:\Run\Python37**
    and it is added to **PATH** environment variable.
3) From command line I call        **pip install yapic.json**
    Which installs    yapic.json   v1.6.3
    Everything looks good.

4) Now I try to run very simple script with call         **python test_yapic.py**
   Here is this script:
   `
   from yapic import json  
   `
   
   This call produces an error. Here is an output:
`
Traceback (most recent call last):
  File "test_yapic.py", line 2, in <module>
    from yapic import json
  File "C:\Run\Python37\lib\site-packages\yapic\json\__init__.py", line 1, in <module>
    from ._json import __version__  # noqa
ImportError: DLL load failed: The specified module could not be found.
`

Any ideas?
Thank you in advance.

**Comment by AntiTenzor** [comment]
After **hours** of investigation I was lucky enough to install Visual Studio redistributable libraries for VS 2015, 2017, 2019
[https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

I feel this is important enough to be clearly stated at the Prerequisite section.

Btw, thank you for your excellent library! =)

**Comment by zozzz** [comment]
Thank you for your effort! I updating the docs, but maybe better to the remove the dependency.

**Comment by AntiTenzor** [comment]
VS redist is not a big deal.
But I will make a tatoo they are 'must have' at every fresh deploy. =)
