### ISSUE TITLE
Segmentation fault due to negative ref count on broken json input 

### ISSUE THREAD

**Issue by agijsberts** [zozzz/yapic.json#16]
## Description
An interrupted json of a dictionary causes a negative ref count and therefore a segmentation fault.

## Example
```python
from yapic import json
s = '{"foo":"bar","baz'
json.loads(s)
```
## Output
One would expect exception `yapic.json.JsonDecodeError: Unexpected end of data at position: 17.` with no other side effects. Instead with normal python we get a segmentation fault. With python with debug symbols we get:
```
../Include/object.h:497: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x7f04a0c37ae0 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized
yapic.json.JsonDecodeError: Unexpected end of data at position: 17.

Current thread 0x00007f04a10c2740 (most recent call first):
  File "/home/user/dev/git/rtdata/yapic_segfault.py", line 3 in <module>
Aborted
```
So the exception is raised correctly, but hidden due to a superfluous reference decrement. GDB seems to indicate  https://github.com/zozzz/yapic.json/blob/master/src/decoder.h#L956 as the culprit, which I guess would make sense.

## Environment
Latest wheel from PyPi (1.7.0) and latest git (1.6.3, strangely enough) on linux.

**Comment by zozzz** [comment]
Thanks your effort for details. I release it to PyPi soon.

**Comment by agijsberts** [comment]
Happy to help and sorry that I didn't manage accompany it with a fix. Thanks for the extremely quick solution!
