### ISSUE TITLE
Exception class compatibility with builtin `json` module

### ISSUE THREAD

**Issue by char101** [zozzz/yapic.json#18]
Hi,

The error exception class name in the builtin `json` module is `JSONDecodeError`, while the exception class in this module is `JsonDecodeError`. If you could provide an alias `JSONDecodeError = JsonDecodeError` in this module (probably in `__init__.py`) it would make it easier to migrate between the two json modules and reduce typing error.

**Comment by zozzz** [comment]
This is a little bit more complicated. If I/You/Others wants full compatibility with `JSONDecodeError` i need to implement other parts of exception:

```python
class JSONDecodeError(ValueError):
    msg: str
    doc: str
    pos: str
    lineno: int
    colno: int
```

So i thinking of implement the following error hierarchy:

```python
class JsonError(ValueError):  # easy - changed, currently inherits from Exception
    pass

class JsonEncodeError(JsonError):  # easy - unchanged
    pass

class JsonDecodeError(JsonError, JSONDecodeError):  # complicated part
    pass
```

And after you can match excpetion in this way:

```python
try:
    yapic.json.loads("{")
except JSONDecodeError:
    pass

# or

try:
    yapic.json.loads("{")
except yapic.json.JsonDecodeError:
    pass
```

**Comment by char101** [comment]
What happened in my case is usually like this

Original code

```python
import json

try:
  json.loads("str")
except json.JSONDecodeError:
  pass
```

When I switched to using `yapic.json`

```python
from yapic import json # easy, just add from yapic import ...

try:
  json.loads("str")
except json.JSONDecodeError: # exception not catched here because wrong exception class name and python does not check that yapic.json.JSONDecodeError actually exists at compile time
  pass
```

So in my case it is really only the class name case that is the problem. 

On the other hand if we want full compatibility in the exception hierarchy I agree that it could become more complicated.
