### ISSUE TITLE
UTF-8 Decoding?

### ISSUE THREAD

**Issue by bmoscon** [zozzz/yapic.json#2]
The Readme states:

```
UTF-8 encoding & decoding support
```

But when I try and load a simple bytestring it fails:

```python
from yapic import json
json.loads(b'{"a": 1}')

TypeError  
Traceback (most recent call last)
<ipython-input-5-c9f0bd3ca33c> in <module>
----> 1 json.loads(b'{"a": 1}')

TypeError: argument 1 must be str, not bytes
```

whereas with CPython json, this works:

```python
import json as j

j.loads(b'{"a": 1}')

Out: {'a': 1}
```

What am I missing? Is there a kwarg I need to pass to have it decode?

**Comment by zozzz** [comment]
I simply forgot to implement this functionality, but implement soon.

**Comment by bmoscon** [comment]
@zozzz ok - thanks for the update. Looking forward to this feature
