### ISSUE TITLE
bytearray support 

### ISSUE THREAD

**Issue by kaber2** [zozzz/yapic.json#9]
I'm using yapic.json to decode data received from a socket. For performance reasons, I'd like to switch to using recv_into with bytearrays, however yapic.json doesn't support decoding bytearrays.

The change itself seems quite trivial, however I did not manager to compile it myself because it fails to find the yapic.core headers for some reason.

**Comment by zozzz** [comment]
yapic.core header is live in a git submodule, so after you clone this repo, run `git submodule update --init --recursive`

**Comment by kaber2** [comment]
Thanks, I'll give it a try!

**Comment by kaber2** [comment]
This appears to be working fine.

`
diff --git a/src/json.cpp b/src/json.cpp
index 327b770..7717456 100644
--- a/src/json.cpp
+++ b/src/json.cpp
@@ -35,6 +35,11 @@
 	return decoder.Decode(); \
 	}
 
+#define __decode_bytearray(T) { \
+	BytesDecoder<T, Py_UCS4, YAPIC_JSON_BYTES_DECODER_BUFFER_SIZE> decoder((T*) PyByteArray_AS_STRING(input), PyByteArray_GET_SIZE(input)); \
+	__decoder_options \
+	return decoder.Decode(); \
+	}
 
 namespace Yapic { namespace Json {
 
@@ -165,6 +170,8 @@ namespace Yapic { namespace Json {
 				}
 			} else if (PyBytes_Check(input)) {
 				__decode_bytes(Py_UCS1);
+			} else if (PyByteArray_Check(input)) {
+				__decode_bytearray(Py_UCS1);
 			} else {
 				PyErr_SetString(PyExc_TypeError, "argument 1 must be str or bytes");
 			}
`

I'll try to send a proper PR, never done that on github before.

**Comment by zozzz** [comment]
ok

**Comment by zozzz** [comment]
Why not send a PR? If u don't know to do, this is the steps:

- fork my repo
- clone forked repo -- this repo appears under your repos -- (don't forget `git submodule update --init --recursive`)
- make changes
- push changes
- send pr
